---
title: "UTAUT segmentation analysis"
output: html_notebook
---

```{r, cache=TRUE}
# Load the project data  ----
library(semcoa)
library(seminr)
library(rpart)

utaut_mm <- constructs(
  composite("PE", multi_items("PERF", 1:4)),
  composite("EE", c("PEOU1","PEOU3","PEOU5","PEOU6")),
  composite("SI", c(multi_items("NORM", 1:2),"INFL3")),
  composite("FC", multi_items("FACL", 1:4)),
  composite("HM", multi_items("MOTIV", 1:3)),
  composite("PV", multi_items("VALUE", 1:3)),
  composite("HAB", multi_items("HAB", 1:4)),
  composite("BI", multi_items("INT", 1:3)),
  composite("Exp", single_item("Experience")),
  composite("Age", single_item("age")),
  composite("Gender", single_item("gender"))
)

utaut_sm <- relationships(
  paths(from = c("PE","EE","SI","FC","HM","PV","HAB","Exp","Age","Gender"), 
        to = "BI")
)

# Estimate model and run deviance trees
utaut_data <- read.csv(file = "../data/trello_utaut.csv")[,-66]

utaut_model <- estimate_pls(data = utaut_data,
                            measurement_model = utaut_mm,
                            structural_model = utaut_sm)
```

Composite Overfit Analysis (COA):
  
```{r, cache=TRUE}
utaut_overfit <- coa(pls_model = utaut_model, 
                     focal_construct = "BI",
                     params = c("path_coef", "outer_weights", "rSquared"))
```

Finding Viable Predictive Segments:

```{r}
segments <- model_segments(utaut_overfit)
```

Analyzing VIABILITY of Segments (can they be estimated?)

```{r}
segment_size <- sapply(segments$node_cases, length)
segment_size[as.character(1:15)]
```

Analyzing DISCRIMINABILITY of Viable Segments:

```{r}
set.seed(37895620)
sim_splits <- replicate(1000, semcoa:::random_split_corrs(utaut_overfit$pls_model, segments$node_cases, 1))
```

```{r}
quantile(sim_splits["ab_corr",], probs=c(0.01, 0.05, 0.10))
summary(sim_splits["ab_corr",])
```

```{r}
plot(density(sim_splits["ab_corr",]), xlim=c(0,1))
abline(v=quantile(sim_splits["ab_corr",], probs=c(0.01, 0.99)), lty="dotted")
abline(v=semcoa:::segments_corr2('2', '3', segments$segmented_estimates), col="cornflowerblue", lwd=2)
```


Assess quality of model 
```{r}
preds <- predict_pls(model = utaut_model,
            technique = predict_DA,
            noFolds = 10,
            cores = 8)
```